name: CI
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install jq
        run: sudo apt-get install jq -y 
      - name: generate badge
        run: sh ./scripts/badge.sh;
      - uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          keep_history: true
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
