name: crontab
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  preinstall:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "start"
  generate:
    runs-on: ubuntu-latest
    needs: preinstall
    steps: 
      - uses: actions/checkout@v2
      - run: echo "generate"
