name: From-Travis-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TRAVIS_REPO_SLUG: ${{ github.repository }} 
      TRAVIS_BRANCH: ${{ github.head_ref }} 
      TRAVIS_PULL_REQUEST: ${{ github.event.number }} 
    steps:
      - name: Set ENV variables
        run: |
          echo "::set-env name=TRAVIS_BRANCH::${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}" 
          echo "::set-env name=TRAVIS_SECURE_ENV_VARS::$(if [ -z "${{ secrets.something }}" ]; then echo "false"; else echo "true"; fi)" 
          echo "::set-env name=TRAVIS_EVENT_TYPE::$(if [ "schedule" == "${{ github.event_name }}" ]; then echo "cron"; else echo "${{ github.event_name }}"; fi)" 
      - name: Print Travis ENV vars 
        run: |
          echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"
          echo "TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}"
          echo "TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
          echo "TRAVIS_SECURE_ENV_VARS: ${TRAVIS_SECURE_ENV_VARS}"
      - uses: actions/checkout@v2
      - run: git fetch origin ${{ github.ref }}
      - name: Install JQ
        run: sudo apt install jq -y
      - name: clone repo
        run: git clone --depth=1 -b gh-pages https://github.com/LCTT/TranslateProject/ build && rm -rf build/.git
      - name: run check
        if: ${{ github.event_name == 'pull_request' }}
        run:  sh ./scripts/check.sh;
      - name: run badge
        if: ${{ github.event_name != 'pull_request' }}
        run: sh ./scripts/badge.sh;
      - name: run status
        if: ${{ github.event_name == 'schedule' }}
        run: sh ./scripts/status.sh;
      - uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          keep_history: true
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

